package com.diletta.claropay.scheduling.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import javax.persistence.*;

@DynamoDBTable(tableName="Transactions")
public class Transaction {

    @Id
    @DynamoDBHashKey(attributeName = "transaction_id")
    @DynamoDBAutoGeneratedKey
    private String transactionId;

   @DynamoDBAttribute(attributeName = "account_id")
    private String accountId;

    @DynamoDBAttribute(attributeName="general_transaction_data")
    private String generalTransactionData;

    @DynamoDBAttribute(attributeName="transaction_type")
    private String transactionType;

    @DynamoDBAttribute(attributeName="scheduled_date")
    private String scheduledDate;

    @DynamoDBAttribute(attributeName="transaction_status")
    private String transactionStatus;

    public Transaction(){}

    public Transaction(String accountId, String generalTransactionData, String transactionType, String scheduledDate, String transactionStatus){
        this.accountId = accountId;
        this.generalTransactionData = generalTransactionData;
        this.transactionType = transactionType;
        this.scheduledDate = scheduledDate;

        this.transactionStatus = transactionStatus;
    }

    public String getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    public String getTransactionStatus() {
        return transactionStatus;
    }

    public void setTransactionStatus(String transactionStatus) {
        this.transactionStatus = transactionStatus;
    }

    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    public String getGeneralTransactionData() {
        return generalTransactionData;
    }

    public void setGeneralTransactionData(String generalTransactionData) {
        this.generalTransactionData = generalTransactionData;
    }

    public String getTransactionType() {
        return transactionType;
    }

    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    public String getScheduledDate() {
        return scheduledDate;
    }

    public void setScheduledDate(String scheduledDate) {
        this.scheduledDate = scheduledDate;
    }

    @Override
    public String toString() {
        return "Transaction{" +
                "transactionId='" + transactionId + '\'' +
                ", accountId='" + accountId + '\'' +
                ", generalTransactionData='" + generalTransactionData + '\'' +
                ", transactionType='" + transactionType + '\'' +
                ", scheduledDate='" + scheduledDate + '\'' +
                ", transactionStatus='" + transactionStatus + '\'' +
                '}';
    }
}
